### ISSUE TITLE
Two identically named MIDI devices - can't open both.

### ISSUE THREAD

**Issue by borfo** [olemb/mido#39] opened 2016-03-29 08:14 UTC
Hi - I'm trying to write a script using two Korg NanoPAD2 midi controllers.  Both of the controllers show up in Mido (portmidi, linux) with the same name - "nanoPAD2 MIDI 1".  I can't open both as ports in Mido using the port name.  The first device mounts, but when I try to open the second, i get a port is already open error.  

Is there any way to mount based on anything other than the device name?  Could I use the alsa port number somehow?  Is there any other way to invoke open_input() other than with the text string device name?

here's the output of pmidi -l from the command line, showing the port numbers and device names.
 28:0     nanoPAD2                          nanoPAD2 MIDI 1
 36:0     nanoPAD2                          nanoPAD2 MIDI 1

....RT-midi names them like this:  'nanoPAD2 28:0', 'nanoPAD2 36:0' - it works.  Would be nice if Portmidi could work too though.

**Comment by olemb** [comment] 2016-04-02 15:15
This is currently not possible. Mido assumes that port names are unique. Since PortMidi doesn't include ALSA port numbers there is no way for Mido to access them.

You can use ``get_devices()`` to see the port info PortMidi provides:

```python
>>> from mido.backends import portmidi
>>> print(portmidi.get_devices())
[{'is_output': 1, 'id': 0, 'is_input': 0, 'name': 'Midi Through Port-0', 'opened': False, 'interface': 'ALSA'}, {'is_output': 0, 'id': 1, 'is_input': 1, 'name': 'Midi Through Port-0', 'opened': False, 'interface': 'ALSA'}]
```

(I have nothing connected at the moment.)

I could modify the port constructor to accept a device instead of a name. Then you could do:

```python
def is_nanopad(dev):
    return dev['name'].startswith('nanoPAD2')

ports = [mido.open_input(dev) for dev in filter(is_nanopad, portmidi.get_devices())]
```

You would still not get port numbers so there would be no way to tell them apart but it's better than nothing.

I've wanted for a while to add a native ALSA backend but I've put it off because the ALSA sequencer API is pretty complex. RawMidi looks promising though: http://www.alsa-project.org/alsa-doc/alsa-lib/rawmidi.html

**Comment by borfo** [comment] 2016-04-03 19:32
Thanks for the reply (and for your work putting Mido together in the first place) - I can just use RT-Midi for now...  But adding the device support would at least make it possible to connect two identically named devices, so that'd be a useful addition to Mido if you get around to it sometime.

**Comment by olemb** [comment] 2016-04-04 18:30
OK, I've put in on the todo list. It's really easy to implement and a good addition.

**Comment by m-vo** [comment] 2016-05-20 21:07
ls there anything new on this?

**Comment by SeanBeeson** [comment] 2016-05-25 07:31
Hello, 

I am in need of being able to specify multiple ports from ALSA that have the same name as well on Linux. 

/bin/mido-ports give me the following.

[root@x201 ~]# mido-ports

Available input Ports:
    'AudioFire12 MIDI 1'
    'Midi Through Port-0'
    'UM-1SX MIDI 1'
    'UM-3 MIDI 1'
    'UM-3 MIDI 1'
    'UM-3 MIDI 2'
    'UM-3 MIDI 2'
    'UM-3 MIDI 3'
    'UM-3 MIDI 3'
    'nanoKEY2 MIDI 1'

Available output Ports:
    'AudioFire12 MIDI 1'
    'Midi Through Port-0'
    'UM-1SX MIDI 1'
    'UM-3 MIDI 1'
    'UM-3 MIDI 1'
    'UM-3 MIDI 2'
    'UM-3 MIDI 2'
    'UM-3 MIDI 3'
    'UM-3 MIDI 3'
    'nanoKEY2 MIDI 1'
    'qjackctl'

Having some way to differentiate these would be great. :)  

I have often seen an inexpensive generic USB MIDI interface show as "USB MIDI Interface MIDI 1" while using two or more for each one. 

It seems the name for any device from a manufacturer will always show up with the same name for each duplicate of the device being used.  

Kind regards,

Sean

**Comment by SeanBeeson** [comment] 2016-05-26 05:51
Hello again,

Is using mido.backends.rtmidi known to be a workaround for this by chance?

Kind regards,

Sean

**Comment by olemb** [comment] 2016-05-27 16:52
@SeanBeeson It looks like it might!

RtMidi adds ALSA device numbers to the port name:

    >>> import mido
    >>> mido.set_backend('mido.backends.rtmidi')
    >>> mido.get_input_names()
    ['Midi Through 14:0']
    >>> mido.get_output_names()
    ['Midi Through 14:0']

These should be unique.

**Comment by SeanBeeson** [comment] 2016-06-07 07:10
Hi, 

Thank you.

**Closed** 2017-02-11 08:49 UTC
